repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
    -   id: cargo-check
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: 97a46d9
    hooks:
    - id: pretty-format-toml
      args: [--autofix, --indent, '4']
      types: [toml]
