[core]

[[coefficients]]
coefficient = -10
field = "tag"
value = "main"

[[coefficients]]
coefficient = -1
field = "depends"

[report.all]
column_names = ["Status", "UUID", "Date Created", "Date Completed", "Summary", "Tags"]
columns = ["status", "uuid", "date_created", "date_completed", "summary", "tags"]
default = false
filters = []

[report.default]
column_names = ["ID", "Date", "Summary", "Due", "Tags", "Urgency"]
columns = ["id", "date_created", "summary", "date_due", "tags", "urgency"]
default = true
filters = ['status:pending or status:active']

[cli]

[[colours]]
bg = "#282c34"
field = "primary_colour"

[[colours]]
fg = "#33bbff"
field = "active"

[[colours]]
bg = "#1a1a1a"
fg = "#ffd966"
field = "tag"
value = "main"

[[colours]]
fg = "#ff99d1"
field = "depends"
value = "hello"

[cli.section]
type = "filters"
colour_palette = ["#ff99d1", "#33bbff", "#ffd966"]

[cli.section.filters]
section1 = ["bar"]
section2 = ["foo or proj:foo"]
"section with +main tag" = ["+main"]
