[[colours]]
bg = "#282c34"
field = "primary_colour"

[[colours]]
bg = "#1a1a1a"
fg = "#ffd966"
field = "tag"
value = "main"

[[colours]]
fg = "#12FF25"
field = "tag"
value = "hello"

[[colours]]
fg = "#ff99d1"
field = "depends"
value = "hello"

[report.all]
column_names = ["UUID", "Date Created", "Date Completed", "Summary", "Tags"]
columns = ["uuid", "date_created", "date_completed", "summary", "tags"]
default = false
filters = []

[report.default]
column_names = ["ID", "Summary", "Tags", "Date", "Urgency"]
columns = ["id", "summary", "tags", "date_created", "urgency"]
default = true
filters = ['status:pending']
