[report.List]
column_names = ["ID", "UUID", "Description", "Tags", "date"]
columns = ["id", "uuid", "description", "tags", "date_created"]
default = true
filters = ['status:pending']

[report.other]
column_names = ["ID", "UUID", "Date Created", "Description", "Tags"]
columns = ["id", "uuid", "date_created", "description", "tags"]
default = false
filters = ['status:pending', "test", "-main"]
