[[coefficients]]
coefficient = -10
field = "tag"
value = "main"

[[coefficients]]
coefficient = -1
field = "depends"

[[colours]]
bg = "#282c34"
field = "primary_colour"

[[colours]]
bg = "#1a1a1a"
fg = "#ffd966"
field = "tag"
value = "main"

[[colours]]
fg = "#ff99d1"
field = "depends"
value = "hello"

[report.all]
column_names = ["Status", "UUID", "Date Created", "Date Completed", "Summary", "Tags"]
columns = ["status", "uuid", "date_created", "date_completed", "summary", "tags"]
default = false
filters = []

[report.default]
column_names = ["ID", "Date", "Project", "Summary", "Due", "Tags", "Urgency"]
columns = ["id", "date_created", "project", "summary", "date_due", "tags", "urgency"]
default = true
filters = ['status:pending']
