//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

pub mod annotations;
pub mod attachments;
pub mod email_links;
pub mod external_links;
pub mod history;
pub mod important_links;
pub mod links;
pub mod projects;
pub mod tags;
pub mod tasks;
pub mod tasks_tags;
pub mod undo_actions;
pub mod user_reports;
