//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

pub use super::annotations::Entity as Annotations;
pub use super::attachments::Entity as Attachments;
pub use super::external_links::Entity as ExternalLinks;
pub use super::history::Entity as History;
pub use super::links::Entity as Links;
pub use super::projects::Entity as Projects;
pub use super::tags::Entity as Tags;
pub use super::tasks::Entity as Tasks;
pub use super::tasks_tags::Entity as TasksTags;
