//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "tasks")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub db_id: i32,
    #[sea_orm(unique)]
    pub id: Option<i32>,
    pub status: String,
    pub uuid: String,
    pub summary: String,
    pub date_created: String,
    pub date_completed: Option<String>,
    pub date_due: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub urgency: Option<f64>,
    pub project_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::annotations::Entity")]
    Annotations,
    #[sea_orm(has_many = "super::history::Entity")]
    History,
    #[sea_orm(
        belongs_to = "super::projects::Entity",
        from = "Column::ProjectId",
        to = "super::projects::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Projects,
    #[sea_orm(has_many = "super::tasks_tags::Entity")]
    TasksTags,
}

impl Related<super::annotations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Annotations.def()
    }
}

impl Related<super::history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::History.def()
    }
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Projects.def()
    }
}

impl Related<super::tasks_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TasksTags.def()
    }
}

impl Related<super::tags::Entity> for Entity {
    fn to() -> RelationDef {
        super::tasks_tags::Relation::Tags.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::tasks_tags::Relation::Tasks.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
