included:
  - Sources
  - Tests

excluded:
  - .build
  - DerivedData
  - .swiftpm

line_length:
  warning: 120
  error: 150

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

disabled_rules:
  - trailing_comma

opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional
