//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "links")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub from_task_id: i32,
    pub to_task_id: i32,
    pub r#type: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tasks::Entity",
        from = "Column::ToTaskId",
        to = "super::tasks::Column::DbId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Tasks2,
    #[sea_orm(
        belongs_to = "super::tasks::Entity",
        from = "Column::FromTaskId",
        to = "super::tasks::Column::DbId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Tasks1,
}

impl ActiveModelBehavior for ActiveModel {}
